### ISSUE TITLE
Using Eigen library in the backdrop_last_layer.cc

### ISSUE THREAD

**Issue by abucka** [google-coral/libcoral#16]
### Description

Hi,

I am running the code from coral/examples/backprop_last_layer.cc on my PC with Ubuntu 18.04 and I get "double free or corruption" error from the Eigen library. The code is stopped on the line from Eigen/src/Core/util/Memory.h in the aligned_free function: `free(ptr)`. I am using the Eigen library from third party folder of the TensorFlow 2.6 repository.

Could you please help me fix this problem? Which Eigen library version should I use? 

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Ubuntu

### Programming Language

C++

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi @abucka can you try with Tensorflow 2.5.0 repository. https://github.com/google-coral/libedgetpu/blob/master/workspace.bzl#L9

**Comment by abucka** [comment]
Hi @hjonnala, thank you for your reply, I used TensorFlow 2.5.0 repo but unfortunately I get another error:

undefined reference to tflite::ConvertBuiltinCodeToDeprecatedBuiltinCode(teilte::BuiltinOperator)

Do you have maybe solution to that problem? Thanks!

**Comment by abucka** [comment]
it works with TF 2.6 when I comment out the `free(ptr)` line in the Eigen lib, but it's probably not the best solution...

**Comment by hjonnala** [comment]
@abucka  Can you please try docker-shell to build backprop_last_layer.cc with TF2.5.0. Please try following

cd libcoral
make docker-shell
make examples ( make inside the docker shell)

**Comment by abucka** [comment]
I built the examples, could you please tell me how can I execute backdrop_last_layer with new parameters? Thanks!

**Comment by hjonnala** [comment]
Hi @abucka here is the example command to run:

`hemanth@hemanth-glaptop:~/libcoral/out/k8/examples$ ./backprop_last_layer --embedding_extractor_path ../../test_data/mobilenet_v1_1.0_224_quant_embedding_extractor_edgetpu.tflite --data_dir ../../retrain/flower_photos --output_model_path ../../trained_model_edgetpu.tflite`

Please check these [instructions](https://github.com/google-coral/libcoral/blob/master/coral/examples/backprop_last_layer.cc#L23) for data preparation. It seems the script is missing saving the model output to file. Please add the the below lines and try the script:
https://github.com/hjonnala/libcoral/blob/master/coral/examples/backprop_last_layer.cc#L49
https://github.com/hjonnala/libcoral/blob/master/coral/examples/backprop_last_layer.cc#L249

Thanks!

**Comment by abucka** [comment]
Thank you very much, it works! 
I would like to call the functions from the backdrop_last_layer in C++ in a QT creator project, do you know how I could do that?

**Comment by Namburger** [comment]
@abucka I haven't used qtcreator yet so I cannot tell you in details, but you can follow the tutorial here to see how to add a new library to a qtcreator project: https://doc.qt.io/qtcreator/creator-project-qmake-libraries.html

Since I'm not 100% sure what you're trying to do, I imagine you want a UI to connect to the functionality provided by our backprop engine? 
If so my suggestion is to write your UI first and then go ahead and copy the source code from [here](https://github.com/google-coral/libcoral/tree/master/coral/learn/backprop) to your project. Since our backprop is just an example of how to use it, you'll most likely have to learn the API and integrate it to your own application instead of just using the binary.

**Comment by abucka** [comment]
Thank you very much for all your help! I managed to use the functions from backdrop script after adjusting the source code and the bazel build file from examples directory, i.e. I generated shared object library instead of the executable.

**Comment by Namburger** [comment]
woot!!
